### PR TITLE
Update ShippingEstimateForm and associated Test

### PR DESCRIPTION
**Pull request by AntonyThorpe**
Used the getCountryField method of the Shop's Address model to create either a dropdown or a readonly field for the Country field in the form.

Updated ShippingEstimateFormTests to test submitting with a dropdown field, bad data, and a readonly field.

### CODE REVIEW

**Comment by AntonyThorpe** [comment]
Any advice please regarding this pull request?  The Scrutinizer check was cancelled.

**Comment by AntonyThorpe** [comment]
Any feedback please regarding this pull request?  All tests in Travis pass, however, there is an external code coverage issue with Scrutinizer.

**Comment by markguinn** [comment]
Scrutinizer is the bane of our existence. :) This looks good to me. @jedateach you've contributed directly to it - are you happy with where it stands? I'd prefer that you squash these commits before we merge it in.

**Comment by AntonyThorpe** [comment]
Commits squashed as requested.  Thanks.

**Comment by AntonyThorpe** [comment]
I have just noticed that commit df04729 , already in the Master branch, has ended up within the squashed commits of this branch (CountryReadonlyField).  Sorry, this is my mistake.  I would like to create a new branch to solve this (the old one can be closed).  Please advise.  Thanks.

**Comment by markguinn** [comment]
Bummer. I'm not sure the best way to handle that in git. Feel free to close this PR and make a new one though. 

You might be able to rebase your existing branch back on top of master and just take care of the resulting conflicts (hopefully df04729 wasn't too in-depth) and then force push here.

**Pull request closed without merging**
